### PR TITLE
strapi-cms-development

### PR DESCRIPTION
**Pull request by gneiazmah**

### CODE REVIEW

**Review by gneiazmah — COMMENTED** [review]
submitted the PR with the Strapi changes.

**Comment by gneiazmah** [comment]
Strapi CMS changes

**Comment by doubleedesign** [comment]
Thanks for your PR @gneiazmah. Why are the files for a WordPress installation present if we are going ahead with Strapi?

**Comment by gneiazmah** [comment]
It has merged the old files again. I will try again.

**Review by gneiazmah — COMMENTED** [review]
strapi-cms-development

**Review by gneiazmah — COMMENTED** [review]
merge-strapi-cms-development

**Comment by gneiazmah** [comment]
> Thanks for your PR @gneiazmah. Why are the files for a WordPress installation present if we are going ahead with Strapi?

Error corrected

**Comment by ben-AI-cybersec** [comment]
Readme.md does not have sufficient information to actually run this. After reading strapi docs on their website I was able to run, but got no admin page. Please clarify how to use this if you want to go forward with strapi. Closing PR, but feel free to reopen with changes.

**Pull request closed without merging**
